export { default as Home } from './Home/Home'
export { default as BasesLegales } from './BasesLegales/BasesLegales'
export { default as SorteoOro } from './SorteoOro/SorteoOro'
export { default as SorteoPlata } from './SorteoPlata/SorteoPlata'
export { default as SorteoBronce } from './SorteoBronce/SorteoBronce'
export { default as Ganadores } from './Ganadores/Ganadores'
